
// Example data for Johannesburg areas
const AREA_DATA = 
{
	"data": [
		{"crime": "abduction", "area": "alexandra", "rate": 1},
		{"crime": "abduction", "area": "eldorado park", "rate": 0},
		{"crime": "abduction", "area": "florida", "rate": 0},
		{"crime": "abduction", "area": "hillbrow", "rate": 1},
		{"crime": "abduction", "area": "jhb central", "rate": 1},
		{"crime": "abduction", "area": "linden", "rate": 0},
		{"crime": "abduction", "area": "midrand", "rate": 0},
		{"crime": "abduction", "area": "norwood", "rate": 0},
		{"crime": "abduction", "area": "parkveiw", "rate": 0},
		{"crime": "abduction", "area": "randburg", "rate": 0},
		{"crime": "abduction", "area": "rosebank", "rate": 0},
		{"crime": "abduction", "area": "sandton", "rate": 2},
		{"crime": "abduction", "area": "sophia town", "rate": 0},
		{"crime": "arson", "area": "alexandra", "rate": 16},
		{"crime": "arson", "area": "eldorado park", "rate": 1},
		{"crime": "arson", "area": "florida", "rate": 1},
		{"crime": "arson", "area": "hillbrow", "rate": 3},
		{"crime": "arson", "area": "jhb central", "rate": 2},
		{"crime": "arson", "area": "linden", "rate": 1},
		{"crime": "arson", "area": "midrand", "rate": 0},
		{"crime": "arson", "area": "norwood", "rate": 2},
		{"crime": "arson", "area": "parkveiw", "rate": 0},
		{"crime": "arson", "area": "randburg", "rate": 0},
		{"crime": "arson", "area": "rosebank", "rate": 1},
		{"crime": "arson", "area": "sandton", "rate": 3},
		{"crime": "arson", "area": "sophia town", "rate": 8},
		{"crime": "violent assault", "area": "alexandra", "rate": 1367},
		{"crime": "violent assault", "area": "eldorado park", "rate": 1107},
		{"crime": "violent assault", "area": "florida", "rate": 349},
		{"crime": "violent assault", "area": "hillbrow", "rate": 993},
		{"crime": "violent assault", "area": "jhb central", "rate": 1017},
		{"crime": "violent assault", "area": "linden", "rate": 144},
		{"crime": "violent assault", "area": "midrand", "rate": 104},
		{"crime": "violent assault", "area": "norwood", "rate": 181},
		{"crime": "violent assault", "area": "parkveiw", "rate": 46},
		{"crime": "violent assault", "area": "randburg", "rate": 196},
		{"crime": "violent assault", "area": "rosebank", "rate": 56},
		{"crime": "violent assault", "area": "sandton", "rate": 95},
		{"crime": "violent assault", "area": "sophia town", "rate": 523},
		{"crime": "attempted murder", "area": "alexandra", "rate": 175},
		{"crime": "attempted murder", "area": "eldorado park", "rate": 209},
		{"crime": "attempted murder", "area": "florida", "rate": 95},
		{"crime": "attempted murder", "area": "hillbrow", "rate": 138},
		{"crime": "attempted murder", "area": "jhb central", "rate": 229},
		{"crime": "attempted murder", "area": "linden", "rate": 23},
		{"crime": "attempted murder", "area": "midrand", "rate": 95},
		{"crime": "attempted murder", "area": "norwood", "rate": 20},
		{"crime": "attempted murder", "area": "parkveiw", "rate": 7},
		{"crime": "attempted murder", "area": "randburg", "rate": 30},
		{"crime": "attempted murder", "area": "rosebank", "rate": 1},
		{"crime": "attempted murder", "area": "sandton", "rate": 37},
		{"crime": "attempted murder", "area": "sophia town", "rate": 205},
		{"crime": "attempted sexual offence", "area": "alexandra", "rate": 9},
		{"crime": "attempted sexual offence", "area": "eldorado park", "rate": 5},
		{"crime": "attempted sexual offence", "area": "florida", "rate": 4},
		{"crime": "attempted sexual offence", "area": "hillbrow", "rate": 15},
		{"crime": "attempted sexual offence", "area": "jhb central", "rate": 1},
		{"crime": "attempted sexual offence", "area": "linden", "rate": 4},
		{"crime": "attempted sexual offence", "area": "midrand", "rate": 4},
		{"crime": "attempted sexual offence", "area": "norwood", "rate": 4},
		{"crime": "attempted sexual offence", "area": "parkveiw", "rate": 0},
		{"crime": "attempted sexual offence", "area": "randburg", "rate": 3},
		{"crime": "attempted sexual offence", "area": "rosebank", "rate": 1},
		{"crime": "attempted sexual offence", "area": "sandton", "rate": 2},
		{"crime": "attempted sexual offence", "area": "sophia town", "rate": 0},
		{"crime": "non-residential burglary", "area": "alexandra", "rate": 93},
		{"crime": "non-residential burglary", "area": "eldorado park", "rate": 174},
		{"crime": "non-residential burglary", "area": "florida", "rate": 260},
		{"crime": "non-residential burglary", "area": "hillbrow", "rate": 167},
		{"crime": "non-residential burglary", "area": "jhb central", "rate": 634},
		{"crime": "non-residential burglary", "area": "linden", "rate": 121},
		{"crime": "non-residential burglary", "area": "midrand", "rate": 511},
		{"crime": "non-residential burglary", "area": "norwood", "rate": 93},
		{"crime": "non-residential burglary", "area": "parkveiw", "rate": 101},
		{"crime": "non-residential burglary", "area": "randburg", "rate": 246},
		{"crime": "non-residential burglary", "area": "rosebank", "rate": 61},
		{"crime": "non-residential burglary", "area": "sandton", "rate": 242},
		{"crime": "non-residential burglary", "area": "sophia town", "rate": 192},
		{"crime": "residential burglary", "area": "alexandra", "rate": 424},
		{"crime": "residential burglary", "area": "eldorado park", "rate": 455},
		{"crime": "residential burglary", "area": "florida", "rate": 590},
		{"crime": "residential burglary", "area": "hillbrow", "rate": 181},
		{"crime": "residential burglary", "area": "jhb central", "rate": 148},
		{"crime": "residential burglary", "area": "linden", "rate": 626},
		{"crime": "residential burglary", "area": "midrand", "rate": 710},
		{"crime": "residential burglary", "area": "norwood", "rate": 391},
		{"crime": "residential burglary", "area": "parkveiw", "rate": 421},
		{"crime": "residential burglary", "area": "randburg", "rate": 417},
		{"crime": "residential burglary", "area": "rosebank", "rate": 65},
		{"crime": "residential burglary", "area": "sandton", "rate": 660},
		{"crime": "residential burglary", "area": "sophia town", "rate": 570},
		{"crime": "carjacking", "area": "alexandra", "rate": 264},
		{"crime": "carjacking", "area": "eldorado park", "rate": 299},
		{"crime": "carjacking", "area": "florida", "rate": 196},
		{"crime": "carjacking", "area": "hillbrow", "rate": 132},
		{"crime": "carjacking", "area": "jhb central", "rate": 239},
		{"crime": "carjacking", "area": "linden", "rate": 63},
		{"crime": "carjacking", "area": "midrand", "rate": 372},
		{"crime": "carjacking", "area": "norwood", "rate": 36},
		{"crime": "carjacking", "area": "parkveiw", "rate": 17},
		{"crime": "carjacking", "area": "randburg", "rate": 85},
		{"crime": "carjacking", "area": "rosebank", "rate": 6},
		{"crime": "carjacking", "area": "sandton", "rate": 217},
		{"crime": "carjacking", "area": "sophia town", "rate": 116},
		{"crime": "commercial crime", "area": "alexandra", "rate": 357},
		{"crime": "commercial crime", "area": "eldorado park", "rate": 272},
		{"crime": "commercial crime", "area": "florida", "rate": 714},
		{"crime": "commercial crime", "area": "hillbrow", "rate": 1041},
		{"crime": "commercial crime", "area": "jhb central", "rate": 1601},
		{"crime": "commercial crime", "area": "linden", "rate": 697},
		{"crime": "commercial crime", "area": "midrand", "rate": 2698},
		{"crime": "commercial crime", "area": "norwood", "rate": 657},
		{"crime": "commercial crime", "area": "parkveiw", "rate": 373},
		{"crime": "commercial crime", "area": "randburg", "rate": 1108},
		{"crime": "commercial crime", "area": "rosebank", "rate": 331},
		{"crime": "commercial crime", "area": "sandton", "rate": 2495},
		{"crime": "commercial crime", "area": "sophia town", "rate": 362},
		{"crime": "common assault", "area": "alexandra", "rate": 2336},
		{"crime": "common assault", "area": "eldorado park", "rate": 1668},
		{"crime": "common assault", "area": "florida", "rate": 772},
		{"crime": "common assault", "area": "hillbrow", "rate": 1388},
		{"crime": "common assault", "area": "jhb central", "rate": 1323},
		{"crime": "common assault", "area": "linden", "rate": 250},
		{"crime": "common assault", "area": "midrand", "rate": 821},
		{"crime": "common assault", "area": "norwood", "rate": 388},
		{"crime": "common assault", "area": "parkveiw", "rate": 121},
		{"crime": "common assault", "area": "randburg", "rate": 360},
		{"crime": "common assault", "area": "rosebank", "rate": 50},
		{"crime": "common assault", "area": "sandton", "rate": 720},
		{"crime": "common assault", "area": "sophia town", "rate": 505},
		{"crime": "common robbery", "area": "alexandra", "rate": 344},
		{"crime": "common robbery", "area": "eldorado park", "rate": 331},
		{"crime": "common robbery", "area": "florida", "rate": 295},
		{"crime": "common robbery", "area": "hillbrow", "rate": 1097},
		{"crime": "common robbery", "area": "jhb central", "rate": 1653},
		{"crime": "common robbery", "area": "linden", "rate": 281},
		{"crime": "common robbery", "area": "midrand", "rate": 456},
		{"crime": "common robbery", "area": "norwood", "rate": 158},
		{"crime": "common robbery", "area": "parkveiw", "rate": 324},
		{"crime": "common robbery", "area": "randburg", "rate": 458},
		{"crime": "common robbery", "area": "rosebank", "rate": 93},
		{"crime": "common robbery", "area": "sandton", "rate": 504},
		{"crime": "common robbery", "area": "sophia town", "rate": 153},
		{"crime": "sexual offence", "area": "alexandra", "rate": 4},
		{"crime": "sexual offence", "area": "eldorado park", "rate": 0},
		{"crime": "sexual offence", "area": "florida", "rate": 2},
		{"crime": "sexual offence", "area": "hillbrow", "rate": 2},
		{"crime": "sexual offence", "area": "jhb central", "rate": 2},
		{"crime": "sexual offence", "area": "linden", "rate": 3},
		{"crime": "sexual offence", "area": "midrand", "rate": 2},
		{"crime": "sexual offence", "area": "norwood", "rate": 4},
		{"crime": "sexual offence", "area": "parkveiw", "rate": 0},
		{"crime": "sexual offence", "area": "randburg", "rate": 1},
		{"crime": "sexual offence", "area": "rosebank", "rate": 0},
		{"crime": "sexual offence", "area": "sandton", "rate": 3},
		{"crime": "sexual offence", "area": "sophia town", "rate": 1},
		{"crime": "culpable homicide", "area": "alexandra", "rate": 12},
		{"crime": "culpable homicide", "area": "eldorado park", "rate": 72},
		{"crime": "culpable homicide", "area": "florida", "rate": 41},
		{"crime": "culpable homicide", "area": "hillbrow", "rate": 41},
		{"crime": "culpable homicide", "area": "jhb central", "rate": 40},
		{"crime": "culpable homicide", "area": "linden", "rate": 13},
		{"crime": "culpable homicide", "area": "midrand", "rate": 82},
		{"crime": "culpable homicide", "area": "norwood", "rate": 16},
		{"crime": "culpable homicide", "area": "parkveiw", "rate": 14},
		{"crime": "culpable homicide", "area": "randburg", "rate": 19},
		{"crime": "culpable homicide", "area": "rosebank", "rate": 2},
		{"crime": "culpable homicide", "area": "sandton", "rate": 52},
		{"crime": "culpable homicide", "area": "sophia town", "rate": 13},
		{"crime": "dui", "area": "alexandra", "rate": 287},
		{"crime": "dui", "area": "eldorado park", "rate": 202},
		{"crime": "dui", "area": "florida", "rate": 197},
		{"crime": "dui", "area": "hillbrow", "rate": 696},
		{"crime": "dui", "area": "jhb central", "rate": 823},
		{"crime": "dui", "area": "linden", "rate": 399},
		{"crime": "dui", "area": "midrand", "rate": 1031},
		{"crime": "dui", "area": "norwood", "rate": 134},
		{"crime": "dui", "area": "parkveiw", "rate": 175},
		{"crime": "dui", "area": "randburg", "rate": 450},
		{"crime": "dui", "area": "rosebank", "rate": 71},
		{"crime": "dui", "area": "sandton", "rate": 313},
		{"crime": "dui", "area": "sophia town", "rate": 171},
		{"crime": "drug-related crime", "area": "alexandra", "rate": 377},
		{"crime": "drug-related crime", "area": "eldorado park", "rate": 915},
		{"crime": "drug-related crime", "area": "florida", "rate": 589},
		{"crime": "drug-related crime", "area": "hillbrow", "rate": 483},
		{"crime": "drug-related crime", "area": "jhb central", "rate": 2003},
		{"crime": "drug-related crime", "area": "linden", "rate": 145},
		{"crime": "drug-related crime", "area": "midrand", "rate": 485},
		{"crime": "drug-related crime", "area": "norwood", "rate": 95},
		{"crime": "drug-related crime", "area": "parkveiw", "rate": 31},
		{"crime": "drug-related crime", "area": "randburg", "rate": 88},
		{"crime": "drug-related crime", "area": "rosebank", "rate": 9},
		{"crime": "drug-related crime", "area": "sandton", "rate": 231},
		{"crime": "drug-related crime", "area": "sophia town", "rate": 1941},
		{"crime": "illegal possession of firearms and ammunition", "area": "alexandra", "rate": 110},
		{"crime": "illegal possession of firearms and ammunition", "area": "eldorado park", "rate": 117},
		{"crime": "illegal possession of firearms and ammunition", "area": "florida", "rate": 51},
		{"crime": "illegal possession of firearms and ammunition", "area": "hillbrow", "rate": 147},
		{"crime": "illegal possession of firearms and ammunition", "area": "jhb central", "rate": 288},
		{"crime": "illegal possession of firearms and ammunition", "area": "linden", "rate": 14},
		{"crime": "illegal possession of firearms and ammunition", "area": "midrand", "rate": 62},
		{"crime": "illegal possession of firearms and ammunition", "area": "norwood", "rate": 29},
		{"crime": "illegal possession of firearms and ammunition", "area": "parkveiw", "rate": 17},
		{"crime": "illegal possession of firearms and ammunition", "area": "randburg", "rate": 13},
		{"crime": "illegal possession of firearms and ammunition", "area": "rosebank", "rate": 1},
		{"crime": "illegal possession of firearms and ammunition", "area": "sandton", "rate": 32},
		{"crime": "illegal possession of firearms and ammunition", "area": "sophia town", "rate": 143},
		{"crime": "kidnapping", "area": "alexandra", "rate": 86},
		{"crime": "kidnapping", "area": "eldorado park", "rate": 223},
		{"crime": "kidnapping", "area": "florida", "rate": 132},
		{"crime": "kidnapping", "area": "hillbrow", "rate": 108},
		{"crime": "kidnapping", "area": "jhb central", "rate": 295},
		{"crime": "kidnapping", "area": "linden", "rate": 39},
		{"crime": "kidnapping", "area": "midrand", "rate": 257},
		{"crime": "kidnapping", "area": "norwood", "rate": 22},
		{"crime": "kidnapping", "area": "parkveiw", "rate": 14},
		{"crime": "kidnapping", "area": "randburg", "rate": 134},
		{"crime": "kidnapping", "area": "rosebank", "rate": 3},
		{"crime": "kidnapping", "area": "sandton", "rate": 112},
		{"crime": "kidnapping", "area": "sophia town", "rate": 57},
		{"crime": "malicious damage to property", "area": "alexandra", "rate": 1019},
		{"crime": "malicious damage to property", "area": "eldorado park", "rate": 1170},
		{"crime": "malicious damage to property", "area": "florida", "rate": 372},
		{"crime": "malicious damage to property", "area": "hillbrow", "rate": 467},
		{"crime": "malicious damage to property", "area": "jhb central", "rate": 482},
		{"crime": "malicious damage to property", "area": "linden", "rate": 199},
		{"crime": "malicious damage to property", "area": "midrand", "rate": 239},
		{"crime": "malicious damage to property", "area": "norwood", "rate": 171},
		{"crime": "malicious damage to property", "area": "parkveiw", "rate": 62},
		{"crime": "malicious damage to property", "area": "randburg", "rate": 212},
		{"crime": "malicious damage to property", "area": "rosebank", "rate": 75},
		{"crime": "malicious damage to property", "area": "sandton", "rate": 252},
		{"crime": "malicious damage to property", "area": "sophia town", "rate": 476},
		{"crime": "murder", "area": "alexandra", "rate": 201},
		{"crime": "murder", "area": "eldorado park", "rate": 152},
		{"crime": "murder", "area": "florida", "rate": 92},
		{"crime": "murder", "area": "hillbrow", "rate": 254},
		{"crime": "murder", "area": "jhb central", "rate": 270},
		{"crime": "murder", "area": "linden", "rate": 14},
		{"crime": "murder", "area": "midrand", "rate": 45},
		{"crime": "murder", "area": "norwood", "rate": 4},
		{"crime": "murder", "area": "parkveiw", "rate": 3},
		{"crime": "murder", "area": "randburg", "rate": 16},
		{"crime": "murder", "area": "rosebank", "rate": 1},
		{"crime": "murder", "area": "sandton", "rate": 19},
		{"crime": "murder", "area": "sophia town", "rate": 105},
		{"crime": "neglect and ill-treatment of children", "area": "alexandra", "rate": 26},
		{"crime": "neglect and ill-treatment of children", "area": "eldorado park", "rate": 19},
		{"crime": "neglect and ill-treatment of children", "area": "florida", "rate": 3},
		{"crime": "neglect and ill-treatment of children", "area": "hillbrow", "rate": 56},
		{"crime": "neglect and ill-treatment of children", "area": "jhb central", "rate": 24},
		{"crime": "neglect and ill-treatment of children", "area": "linden", "rate": 6},
		{"crime": "neglect and ill-treatment of children", "area": "midrand", "rate": 13},
		{"crime": "neglect and ill-treatment of children", "area": "norwood", "rate": 6},
		{"crime": "neglect and ill-treatment of children", "area": "parkveiw", "rate": 0},
		{"crime": "neglect and ill-treatment of children", "area": "randburg", "rate": 3},
		{"crime": "neglect and ill-treatment of children", "area": "rosebank", "rate": 0},
		{"crime": "neglect and ill-treatment of children", "area": "sandton", "rate": 5},
		{"crime": "neglect and ill-treatment of children", "area": "sophia town", "rate": 21},
		{"crime": "public violence", "area": "alexandra", "rate": 7},
		{"crime": "public violence", "area": "eldorado park", "rate": 9},
		{"crime": "public violence", "area": "florida", "rate": 5},
		{"crime": "public violence", "area": "hillbrow", "rate": 5},
		{"crime": "public violence", "area": "jhb central", "rate": 10},
		{"crime": "public violence", "area": "linden", "rate": 0},
		{"crime": "public violence", "area": "midrand", "rate": 4},
		{"crime": "public violence", "area": "norwood", "rate": 2},
		{"crime": "public violence", "area": "parkveiw", "rate": 1},
		{"crime": "public violence", "area": "randburg", "rate": 0},
		{"crime": "public violence", "area": "rosebank", "rate": 1},
		{"crime": "public violence", "area": "sandton", "rate": 4},
		{"crime": "public violence", "area": "sophia town", "rate": 1},
		{"crime": "rape", "area": "alexandra", "rate": 265},
		{"crime": "rape", "area": "eldorado park", "rate": 147},
		{"crime": "rape", "area": "florida", "rate": 74},
		{"crime": "rape", "area": "hillbrow", "rate": 220},
		{"crime": "rape", "area": "jhb central", "rate": 201},
		{"crime": "rape", "area": "linden", "rate": 49},
		{"crime": "rape", "area": "midrand", "rate": 110},
		{"crime": "rape", "area": "norwood", "rate": 25},
		{"crime": "rape", "area": "parkveiw", "rate": 12},
		{"crime": "rape", "area": "randburg", "rate": 66},
		{"crime": "rape", "area": "rosebank", "rate": 11},
		{"crime": "rape", "area": "sandton", "rate": 117},
		{"crime": "rape", "area": "sophia town", "rate": 67},
		{"crime": "non-residential robbery", "area": "alexandra", "rate": 50},
		{"crime": "non-residential robbery", "area": "eldorado park", "rate": 113},
		{"crime": "non-residential robbery", "area": "florida", "rate": 129},
		{"crime": "non-residential robbery", "area": "hillbrow", "rate": 157},
		{"crime": "non-residential robbery", "area": "jhb central", "rate": 429},
		{"crime": "non-residential robbery", "area": "linden", "rate": 39},
		{"crime": "non-residential robbery", "area": "midrand", "rate": 166},
		{"crime": "non-residential robbery", "area": "norwood", "rate": 26},
		{"crime": "non-residential robbery", "area": "parkveiw", "rate": 23},
		{"crime": "non-residential robbery", "area": "randburg", "rate": 110},
		{"crime": "non-residential robbery", "area": "rosebank", "rate": 14},
		{"crime": "non-residential robbery", "area": "sandton", "rate": 53},
		{"crime": "non-residential robbery", "area": "sophia town", "rate": 65},
		{"crime": "residential robbery", "area": "alexandra", "rate": 64},
		{"crime": "residential robbery", "area": "eldorado park", "rate": 78},
		{"crime": "residential robbery", "area": "florida", "rate": 129},
		{"crime": "residential robbery", "area": "hillbrow", "rate": 35},
		{"crime": "residential robbery", "area": "jhb central", "rate": 42},
		{"crime": "residential robbery", "area": "linden", "rate": 169},
		{"crime": "residential robbery", "area": "midrand", "rate": 149},
		{"crime": "residential robbery", "area": "norwood", "rate": 54},
		{"crime": "residential robbery", "area": "parkveiw", "rate": 92},
		{"crime": "residential robbery", "area": "randburg", "rate": 90},
		{"crime": "residential robbery", "area": "rosebank", "rate": 18},
		{"crime": "residential robbery", "area": "sandton", "rate": 239},
		{"crime": "residential robbery", "area": "sophia town", "rate": 95},
		{"crime": "robbery of cash in transit", "area": "alexandra", "rate": 0},
		{"crime": "robbery of cash in transit", "area": "eldorado park", "rate": 1},
		{"crime": "robbery of cash in transit", "area": "florida", "rate": 2},
		{"crime": "robbery of cash in transit", "area": "hillbrow", "rate": 0},
		{"crime": "robbery of cash in transit", "area": "jhb central", "rate": 3},
		{"crime": "robbery of cash in transit", "area": "linden", "rate": 0},
		{"crime": "robbery of cash in transit", "area": "midrand", "rate": 1},
		{"crime": "robbery of cash in transit", "area": "norwood", "rate":0 },
		{"crime": "robbery of cash in transit", "area": "parkveiw", "rate": 0},
		{"crime": "robbery of cash in transit", "area": "randburg", "rate": 0},
		{"crime": "robbery of cash in transit", "area": "rosebank", "rate": 0},
		{"crime": "robbery of cash in transit", "area": "sandton", "rate": 0},
		{"crime": "robbery of cash in transit", "area": "sophia town", "rate": 0},
		{"crime": "robbery with aggravating circumstances", "area": "alexandra", "rate": 1052},
		{"crime": "robbery with aggravating circumstances", "area": "eldorado park", "rate": 1266},
		{"crime": "robbery with aggravating circumstances", "area": "florida", "rate": 985},
		{"crime": "robbery with aggravating circumstances", "area": "hillbrow", "rate": 1462},
		{"crime": "robbery with aggravating circumstances", "area": "jhb central", "rate": 2619},
		{"crime": "robbery with aggravating circumstances", "area": "linden", "rate": 514},
		{"crime": "robbery with aggravating circumstances", "area": "midrand", "rate": 1478},
		{"crime": "robbery with aggravating circumstances", "area": "norwood", "rate": 265},
		{"crime": "robbery with aggravating circumstances", "area": "parkveiw", "rate": 260},
		{"crime": "robbery with aggravating circumstances", "area": "randburg", "rate": 657},
		{"crime": "robbery with aggravating circumstances", "area": "rosebank", "rate": 95},
		{"crime": "robbery with aggravating circumstances", "area": "sandton", "rate": 930},
		{"crime": "robbery with aggravating circumstances", "area": "sophia town", "rate": 725},
		{"crime": "sexual assault", "area": "alexandra", "rate": 42},
		{"crime": "sexual assault", "area": "eldorado park", "rate": 49},
		{"crime": "sexual assault", "area": "florida", "rate": 28},
		{"crime": "sexual assault", "area": "hillbrow", "rate": 41},
		{"crime": "sexual assault", "area": "jhb central", "rate": 43},
		{"crime": "sexual assault", "area": "linden", "rate": 15},
		{"crime": "sexual assault", "area": "midrand", "rate": 30},
		{"crime": "sexual assault", "area": "norwood", "rate": 14},
		{"crime": "sexual assault", "area": "parkveiw", "rate": 14},
		{"crime": "sexual assault", "area": "randburg", "rate": 16},
		{"crime": "sexual assault", "area": "rosebank", "rate": 5},
		{"crime": "sexual assault", "area": "sandton", "rate": 33},
		{"crime": "sexual assault", "area": "sophia town", "rate": 36},
		{"crime": "shoplifting", "area": "alexandra", "rate": 361},
		{"crime": "shoplifting", "area": "eldorado park", "rate": 397},
		{"crime": "shoplifting", "area": "florida", "rate": 197},
		{"crime": "shoplifting", "area": "hillbrow", "rate": 234},
		{"crime": "shoplifting", "area": "jhb central", "rate": 749},
		{"crime": "shoplifting", "area": "linden", "rate": 283},
		{"crime": "shoplifting", "area": "midrand", "rate": 610},
		{"crime": "shoplifting", "area": "norwood", "rate": 140},
		{"crime": "shoplifting", "area": "parkveiw", "rate": 9},
		{"crime": "shoplifting", "area": "randburg", "rate": 205},
		{"crime": "shoplifting", "area": "rosebank", "rate": 196},
		{"crime": "shoplifting", "area": "sandton", "rate": 543},
		{"crime": "shoplifting", "area": "sophia town", "rate": 218},
		{"crime": "stock-theft", "area": "alexandra", "rate": 0},
		{"crime": "stock-theft", "area": "eldorado park", "rate": 6},
		{"crime": "stock-theft", "area": "florida", "rate": 0},
		{"crime": "stock-theft", "area": "hillbrow", "rate": 0},
		{"crime": "stock-theft", "area": "jhb central", "rate": 0},
		{"crime": "stock-theft", "area": "linden", "rate": 0},
		{"crime": "stock-theft", "area": "midrand", "rate": 3},
		{"crime": "stock-theft", "area": "norwood", "rate": 0},
		{"crime": "stock-theft", "area": "parkveiw", "rate": 0},
		{"crime": "stock-theft", "area": "randburg", "rate": 0},
		{"crime": "stock-theft", "area": "rosebank", "rate": 0},
		{"crime": "stock-theft", "area": "sandton", "rate": 0},
		{"crime": "stock-theft", "area": "sophia town", "rate": 0},
		{"crime": "Theft of motor vehicle and motorcycle", "area": "alexandra", "rate": 202},
		{"crime": "Theft of motor vehicle and motorcycle", "area": "eldorado park", "rate": 126},
		{"crime": "Theft of motor vehicle and motorcycle", "area": "florida", "rate": 677},
		{"crime": "Theft of motor vehicle and motorcycle", "area": "hillbrow", "rate": 355},
		{"crime": "Theft of motor vehicle and motorcycle", "area": "jhb central", "rate": 601},
		{"crime": "Theft of motor vehicle and motorcycle", "area": "linden", "rate": 433},
		{"crime": "Theft of motor vehicle and motorcycle", "area": "midrand", "rate": 342},
		{"crime": "Theft of motor vehicle and motorcycle", "area": "norwood", "rate": 195},
		{"crime": "Theft of motor vehicle and motorcycle", "area": "parkveiw", "rate": 369},
		{"crime": "Theft of motor vehicle and motorcycle", "area": "randburg", "rate": 255},
		{"crime": "Theft of motor vehicle and motorcycle", "area": "rosebank", "rate": 74},
		{"crime": "Theft of motor vehicle and motorcycle", "area": "sandton", "rate": 419},
		{"crime": "Theft of motor vehicle and motorcycle", "area": "sophia town", "rate": 274},
		{"crime": "Theft out of or from motor vehicle", "area": "alexandra", "rate": 217},
		{"crime": "Theft out of or from motor vehicle", "area": "eldorado park", "rate": 242},
		{"crime": "Theft out of or from motor vehicle", "area": "florida", "rate": 512},
		{"crime": "Theft out of or from motor vehicle", "area": "hillbrow", "rate": 635},
		{"crime": "Theft out of or from motor vehicle", "area": "jhb central", "rate": 1309},
		{"crime": "Theft out of or from motor vehicle", "area": "linden", "rate": 478},
		{"crime": "Theft out of or from motor vehicle", "area": "midrand", "rate": 1076},
		{"crime": "Theft out of or from motor vehicle", "area": "norwood", "rate": 270},
		{"crime": "Theft out of or from motor vehicle", "area": "parkveiw", "rate": 447},
		{"crime": "Theft out of or from motor vehicle", "area": "randburg", "rate": 648},
		{"crime": "Theft out of or from motor vehicle", "area": "rosebank", "rate": 201},
		{"crime": "Theft out of or from motor vehicle", "area": "sandton", "rate": 749},
		{"crime": "Theft out of or from motor vehicle", "area": "sophia town", "rate": 275},
		{"crime": "Truck hijacking", "area": "alexandra", "rate": 7},
		{"crime": "Truck hijacking", "area": "eldorado park", "rate": 17},
		{"crime": "Truck hijacking", "area": "florida", "rate": 21},
		{"crime": "Truck hijacking", "area": "hillbrow", "rate": 4},
		{"crime": "Truck hijacking", "area": "jhb central", "rate": 16},
		{"crime": "Truck hijacking", "area": "linden", "rate": 0},
		{"crime": "Truck hijacking", "area": "midrand", "rate": 35},
		{"crime": "Truck hijacking", "area": "norwood", "rate": 1},
		{"crime": "Truck hijacking", "area": "parkveiw", "rate": 0},
		{"crime": "Truck hijacking", "area": "randburg", "rate": 23},
		{"crime": "Truck hijacking", "area": "rosebank", "rate": 0},
		{"crime": "Truck hijacking", "area": "sandton", "rate": 15},
		{"crime": "Truck hijacking", "area": "sophia town", "rate": 2},
    ]
}
;

// group crimes
const violentCrimes=[
    "abduction", 
    "arson", 
    "violent assault",
    "attempted murder",
    "attempted sexual offence",
    "carjacking","common assault",
    "common robbery",
    "culpable homicide",
    "kidnapping",
    "murder", 
    "public violence", 
    "rape",
    "robbery with aggravating circumstances", 
    "sexual assault",
    "sexual offence",
];

const propertyCrimes=[
    "non-residential burglary",
    "residential burglary",
    "commercial crime",
    "malicious damage to property",
    "non-residential robbery",
    "residential robbery",
    "robbery of cash in transit",
    "shoplifting",
    "stock-theft",
    "Theft of motor vehicle and motorcycle",
    "Theft out of or from motor vehicle",
    "Truck hijacking",
];

const drugWeaponCrimes=[
    "dui",
    "drug-related crime",
    "illegal possession of firearms and ammunition",
]

const childRelatedCrimes=[
    "neglect and ill-treatment of children",
]

// array of areas
const areas=[
	"alexandra",
	"eldorado park",
	"florida",
	"hillbrow",
	"jhb central",
	"linden",
	"midrand",
	"norwood",
	"parkveiw",
	"randburg",
	"rosebank",
	"sandton",
	"sophia town"
]

// for each area, tally up rate for a certain crime type
const tallyCrimes = (data, crimesType) => {
	const tally = {};
  
	data.forEach(entry => {
	  if (crimesType.includes(entry.crime)) {
		if (!tally[entry.area]) {
		  tally[entry.area] = 0;
		}
		tally[entry.area] += entry.rate;
	  }
	});
  
	return tally;
  };

//tally violent crimes
const violentCrimesTally = tallyCrimes(AREA_DATA.data, violentCrimes);

//tally property crimes
const propertyCrimeTally = tallyCrimes(AREA_DATA.data, propertyCrimes);

//tally drug & weapon crimes
const drugWeaponCrimesTally = tallyCrimes(AREA_DATA.data, drugWeaponCrimes);

//tally child related crimes
const childRelatedCrimesTally = tallyCrimes(AREA_DATA.data, childRelatedCrimes);

function generateHotspots(crimeTally){

    const crimeRates= Object.values(crimeTally);
    const mean = crimeRates.reduce((a, b) => a + b, 0) / crimeRates.length;    
    // Calculate standard deviation
    const variance = crimeRates.reduce((a, b) => a + Math.pow(b - mean, 2), 0) / crimeRates.length;
    const standardDeviation = Math.sqrt(variance);
    const threshold = mean + standardDeviation;

    const hotspots = Object.keys(crimeTally).filter(area => crimeTally[area] > threshold);
    return hotspots;

}


//generate crime hotspots
let violentCrimeHotspots= generateHotspots(violentCrimesTally);
let propertyCrimeHotspots=generateHotspots(propertyCrimeTally);
let drugWeaponHotspots=generateHotspots(drugWeaponCrimesTally);
let childRelatedHotspots=generateHotspots(childRelatedCrimesTally);



export { AREA_DATA,violentCrimeHotspots,propertyCrimeHotspots,drugWeaponHotspots,childRelatedHotspots };

